//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Espresso.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextContainer : DbContext
    {
        public ContextContainer()
            : base("name=ContextContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CoffeePurchase> CoffeePurchases { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<CoffeePurchase_Details> CoffeePurchase_Details { get; set; }
        public virtual DbSet<CoffeeSort> CoffeeSorts { get; set; }
        public virtual DbSet<dGreenStock> dGreenStocks { get; set; }
        public virtual DbSet<Roasting> Roastings { get; set; }
        public virtual DbSet<dRoastedStock> dRoastedStocks { get; set; }
        public virtual DbSet<Mix> Mixes { get; set; }
        public virtual DbSet<Mix_Details> Mix_Details { get; set; }
        public virtual DbSet<Packing> Packings { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<PackagePurchase> PackagePurchases { get; set; }
        public virtual DbSet<dPackedStocks> dPackedStocks { get; set; }
        public virtual DbSet<dPackageStocks> dPackageStocks { get; set; }
        public virtual DbSet<CoffeeSale> CoffeeSales { get; set; }
        public virtual DbSet<Recipient> Recipients { get; set; }
        public virtual DbSet<CoffeeSale_Details> CoffeeSale_Details { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<PackedCategory> PackedCategories { get; set; }
        public virtual DbSet<CoffeeTransfer> CoffeeTransfers { get; set; }
        public virtual DbSet<dCafeCoffeeStock> dCafeCoffeeStocks { get; set; }
    }
}
