//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyExpense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonthlyExpense()
        {
            this.Active = true;
            this.MonthlyPayments = new HashSet<MonthlyPayment>();
        }
    
        public int Id { get; set; }
        public double Amount { get; set; }
        public string Designation { get; set; }
        public int Day { get; set; }
        public int RemindingDay { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> dLastPaidDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlyPayment> MonthlyPayments { get; set; }
    }
}
