//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPurchase
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
        public double Price { get; set; }
        public double dSum { get; set; }
        public int TransactionId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
