//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.SaleDetailsCoffee = new HashSet<SaleDetailCoffee>();
            this.SaleDetailsProducts = new HashSet<SaleDetailProduct>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public bool Paid { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<int> TransactionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleDetailCoffee> SaleDetailsCoffee { get; set; }
        public virtual Recipient Recipient { get; set; }
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleDetailProduct> SaleDetailsProducts { get; set; }
    }
}
